### ISSUE TITLE
I have a few more questions

### ISSUE THREAD

**Issue by LightRO** [nebulabroadcast/nebula#10]
Hello together,

I have now installed it so far.

But now I still have a few questions.

1.) I was able to successfully test the connection to samba on the server, but nebula does not seem to be able to log on to samba. 

2.) Is it possible to send on an rtsp stream and how?

3.) The plugin folder called .nx/scripts/... does not exist, where can I find it?

4.) How do I upload a video?

I know these are actually stupid questions but I can't figure them out from the instructions.

Thanks a lot for the help.
LightRO

**Comment by martastain** [comment]
1) I was able to successfully test the connection to samba on the server, but nebula does not seem to be able to log on to samba.

Samba storages should mount automatically to `/mnt/SITENAME_STORAGEID` is there any error message during nebula start-up? Sometimes samba connection fails when the protocol version is not supported by the server. Nebula by default uses version 3 and you may change it using `samba_version` tag in the storage definition:

For example:

```python
data["storages"][1] = {
     "title"    : "production",
     "protocol" : "samba",
     "path"     : "//storage_server_ip_address/share",
     "login"    : "nebula",
     "password" : "nebula",
     "samba_version" : "2.0"
}
```

2) Yes. But how depends on the playout engine you are using. With Conti, you may tweak the `conti_outputs` section of the channel definition (see FFMpeg documentation - for example https://trac.ffmpeg.org/wiki/StreamingGuide ). With CasparCG, we usually use an external encoder fed by NDI or SDI output from the server, but it should be possible to use "ADD STREAM" command to enable the streaming output directly. ( https://casparcgforum.org/ might help).

3) By default `.nx/scripts/` is expected to be in the root directory of the first storage, but if you don't have any playout plugins, you may safely ignore this warning. I'm working on examples.

4) The easiest way is to use watch folders. See https://github.com/immstudios/nebula-demo/tree/master/settings for a sample configuration.

**Comment by LightRO** [comment]
Point 1 I have already solved :D I had an error in the config anyway many thanks ^^.

Point 2: I do not know yet where and how the config must look exactly but I will try it first ^^.

Point 3: exactly I have the folder .nx/scripts/ unfortunately not at all. I wanted to install the plugin: Dramatica and now I don't know how to do it :D

Point 4: I have already tried that:

in the __init__.py it looks like this

1 : {
        "title" : "production",
        "protocol" : "samba",
        "path" : "//ms097/sambanana/storage1",
        "login" : "username",
        "password" : "password"
    },


and in the Watch.xml


<service>
    <folder id_storage="1" path="/movies"></folder>
</service>

So the full directory would be:

//ms097/sambanana/storage1/movies/.

There is a mp4 file in there and unfortunately I don't see it in firefly or in the web interface

and very many thanks for your perfect help.

**Comment by martastain** [comment]
Let's start with the 4th point first, since you won't get far without uploading media. Could you send me the watch.xml contents please? 

To be sure: is the storage mounted successfully to `/mnt/****_01/` ? What about errors in the logs?

There is also an asset counter on the dashboard page of the web interface - is there still zero? Maybe asset was created, but it's in a different view (by default, watch service saves assets as "incoming" so they are not visible in the "main" view). BTW: you can list all assets regardless the view using the `nxa` command without parameters.

**Comment by LightRO** [comment]
The connection was indeed successful, because in the /mnt/ folder the two directories nebula_01 and nebula_02 exist and from there I also get into the corresponding storage directory ^^
The file: .nebula_root was also created in it.

I do not get any real errors at least not in the output.

`11:21:09	DEBUG    	play@ms097	Initializing service ID 4
11:21:09	DEBUG    	play@ms097	Executing AMCP: version
11:21:09	INFO     	play@ms097	Using CasparCG 2.0.7 info parser
11:21:09	INFO     	play@ms097	Using port 42100 for the HTTP interface.
11:21:09	WARNING  	play@ms097	Playout plugins directory does not exist
11:21:09	GOOD NEWS	play@ms097	Service started
11:21:31	INFO     	hub@ms097	LightRO requested api method jobs
11:21:33	DEBUG    	hub@ms097	Executing get query: SELECT id, meta, 0 FROM assets WHERE id_folder IN (1,2) AND status IN (0,1,2,5,11) ORDER BY id desc LIMIT 101
11:21:36	DEBUG    	hub@ms097	Executing get query: SELECT id, meta, 0 FROM assets WHERE id_folder=12 AND status IN (0,1,2,5,11) ORDER BY id desc LIMIT 101
11:21:37	DEBUG    	hub@ms097	asset ID:7 (4)
11:22:27	DEBUG    	hub@ms097	Executing get query: SELECT id, meta, 0 FROM assets WHERE id_folder IN (1,2) AND status IN (0,1,2,5,11) ORDER BY id desc LIMIT 101
11:22:30	DEBUG    	hub@ms097	Executing get query: SELECT id, meta, 0 FROM assets WHERE id_folder=12 ORDER BY id desc LIMIT 101
11:22:55	INFO     	hub@ms097	LightRO requested api method jobs
11:23:11	DEBUG    	hub@ms097	Executing get query: SELECT id, meta, 0 FROM assets WHERE id_folder IN (1,2) AND status IN (0,1,2,5,11) ORDER BY id desc LIMIT 101
11:31:54	ERROR    	hub@ms097	Error 404 ("actuator" module not found) during processing GET request "/actuator/health"
13:03:45	ERROR    	hub@ms097	Error 404 ("hudson" module not found) during processing GET request "/hudson"
15:38:21	ERROR    	hub@ms097	Error 400 (Bad request) during processing GET request "/login"
17:29:39	DEBUG    	nebula@ms097	Executing get query: SELECT id, meta, count(id) OVER() AS full_count FROM assets ORDER BY id DESC
`

My watch.xml looks like this:

`<service>
    <folder id_storage="1" path="/movies"></folder>
</service>`

The output of the nxa command showed the following:

![image](https://user-images.githubusercontent.com/19392688/114896702-d713da80-9e10-11eb-9f5f-954e70c12c9d.png)

I was able to create the assets all manually they are also under incomming but the video files are not linked to the assets unless the ones that are currently on the server.

many thanks for your help,
LightRO

**Comment by martastain** [comment]
Is there a chance to let me check? Maybe a VNC session to the machine from which I'll be able to SSH to the server (so you'll be able to see what I'm doing)? I'm leaving the office for today (I'm GMT+2) but you can reach me via mail (martin@nebulabroadcast.com) or better Telegram/Skype @martastain .

**Comment by LightRO** [comment]
I have send you a mail with teamviewer access ^^
