### ISSUE TITLE
CHAN ERR spam in logs when CasparCG has ffmpeg consumer

### ISSUE THREAD

**Issue by JulianJacobi** [nebulabroadcast/nebula#14]
Maybe it's not the best idea to hard-error fo every OSC Packet nebula is not able to process.

https://github.com/nebulabroadcast/nebula/blob/d72e069d0177cc3a302a64e27c8fa978a3d4bd27/services/play/casparcg2/caspar_data.py#L75

**Comment by martastain** [comment]
Yeah.... I haven't removed it after i handled all incoming messages from casparcg. I know it is not elegant, but in case it becomes noisy, you'll know you need to handle something new.

**Comment by JulianJacobi** [comment]
OK, yes i see your point, so under this circumstances:

There ist something new to handle:
```
['output', 'port', '163598', 'file', 'frame']
['output', 'port', '163598', 'file', 'path']
```

But i think the output stuff is out of scope for nebula, so maybe the best solution in this case would be:

```python
elif address[0] == "output":
    return False
```
