### ISSUE TITLE
Module nxtools not exist

### ISSUE THREAD

**Issue by LightRO** [nebulabroadcast/nebula#15]
I just tried installing everything again myself and after installing all the basics I come to nxadduser. Unfortunately this command does not work because nxtools does not exist. See error message.

`Traceback (most recent call last):
  File "/usr/bin/nxadduser", line 3, in <module>
    from cli import *
  File "/opt/nebula/cli/__init__.py", line 3, in <module>
    import cli.run as run
  File "/opt/nebula/cli/run.py", line 4, in <module>
    from nxtools import xml, critical_error, log_traceback, logging
ModuleNotFoundError: No module named 'nxtools'`

Is there any way to fix this?

Many greetings,
LightRO

**Comment by martastain** [comment]
nxtools is a core requirement, as specified in pyproject.toml and requirements.txt. You have to install all prerequisites first (either using poetry or simply by running `pip3 install -r requirements.txt`
