### ISSUE TITLE
+100% CPU usage after scrubbing a proxy preview

### ISSUE THREAD

**Issue by ianshade** [nebulabroadcast/nebula#41]
Hi! I've seen this issue in two deployments in Docker, both following the [tutorial](https://github.com/nebulabroadcast/nebula-tutorial): on Ubuntu 22.04.3 LTS, and on Windows 10 (WSL 2). Initially, CPU usage of the backend container looks reasonable (between 0 and 10%) when I'm just browsing the assets and gently playing/pausing the previews, but as soon as I start scrubbing, the CPU usage of that container jumps to over 100% and stays at this level even after I close the Firefly client or the browser tab. Memory usage also increases, and it seems to correspond with the size of the proxy file. So far only restarting the backend container helps bring the CPU usage down. It's the same with an SMB share and a docker volume. My gut says it may have something to do with cancelled requests that occur when scrubbing.

https://github.com/nebulabroadcast/nebula/assets/9103996/adaeec00-d1c1-4e0a-a54b-956a843bb9e2

![image](https://github.com/nebulabroadcast/nebula/assets/9103996/7507a9ad-7ae1-47e8-823d-b5b111e3e88c)
![image](https://github.com/nebulabroadcast/nebula/assets/9103996/3e059329-223a-407b-87c8-23e2adf8c01f)
![image](https://github.com/nebulabroadcast/nebula/assets/9103996/6b2b3605-fa8c-40e2-8f0a-9a56fa691d94)

**Comment by ianshade** [comment]
I'm wondering if the exist condition of this loop is correct. Is `pos` ever changing, considering `chs` is assigned once, outside of the loop? 
https://github.com/nebulabroadcast/nebula/blob/86a30c1b73d4dbf262eab6c3dc977b329b776e80/backend/api/proxy.py#L21-L25

**Comment by martastain** [comment]
I think you're right. After changing this part i can no longer reproduce this issue. Do you have a chance to test it with the linked PR? You can also set `NEBULA_LOG_LEVEL=trace` environment variable to check whether all requests are properly finished. 

CPU utilization seems to drop next to zero eventually (it takes longer with firefly as libmpv uses a longer buffer). I missed this - in can see Cpu spikes in production servers, but no one ever complained as the utilization was never high enough to cause major issues, so even in multi-user environment no one complained.

Thanks for your research!

**Comment by martastain** [comment]
Please reopen this if the problem persists in `nebula-server:6.0.3`
